Homework 4. Factorial. Recursion. Fibonacci
Alexy-Def/TMS.Net07.Homework pull request #3
Opened 2021-02-07 18:54 UTC by Alexy-Def

<h1>Homework 4: Factorial. Recursion. Fibonacci</h1>

_**This program should calculate:**_ 
1. The factorial;
1. The factorial with recursion;
1. Fibonacci numbers by any method;
1. Fast method of calculate Fibonacci numbers .

2021-02-11 18:32 UTC, radzevich requested changes

2021-02-11 18:32 UTC, radzevich commented on TMS.Net07.Homework4.RecursionAndFibonacci/TMS.Net07.Homework4.Task4.Fibonacci/TMS.Net07.Homework4.Task4.Fibonacci/Program.cs
> +                    if (isTryInputNumber == false)
```suggestion
                    if (!isTryInputNumber)
```
Here and other same places

2021-02-12 07:28 UTC, Alexy-Def commented on TMS.Net07.Homework4.RecursionAndFibonacci/TMS.Net07.Homework4.Task4.Fibonacci/TMS.Net07.Homework4.Task4.Fibonacci/Program.cs
> +                    if (isTryInputNumber == false)
I fixed all the mistakes

2021-02-13 09:28 UTC, radzevich approved these changes

2021-02-17 14:24 UTC, merged